@startuml lab4
title Pool

|Customer|
start
:Browses products;
:Starts order;

|Application|
:Creates order with status "Pending";

repeat
  :Adds products to order;
  
  fork
    :Checks product availability;
  fork again
    :Logs user actions;
  end fork

  if () then (Product available)
    :Confirms addition;
  else (Product not available)
    :Shows out-of-stock message;
  endif
repeat while (Wants to add more)

|Customer|
:Confirms order;

|Payment Service|
:Creates payment session;
:Processes payment;

|Application|
if () then (Payment successful)
  :Updates status to "Paid";
else (Payment not successful)
  :Updates status to "Failed";
endif

:Send Payment Status Message;

|Customer|
:Read Payment Status Message;
stop
@enduml
